# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_pageadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAdmin',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 1, 26, 16, 16, 13, 458000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
